DROP TABLE IF EXISTS `favorite` CASCADE;
DROP TABLE IF EXISTS `book` CASCADE;
DROP TABLE IF EXISTS `member` CASCADE;
DROP TABLE IF EXISTS `auth_number` CASCADE;

CREATE TABLE `favorite`
(
    `favorite_id` bigint generated by default as identity,
    `member_id` bigint NOT NULL,
    `book_id`   bigint NOT NULL
);

CREATE TABLE `book`
(
    `book_id`     bigint generated by default as identity,
    `call_number` VARCHAR(255) NOT NULL,
    `book_name`   VARCHAR(255) NULL,
    `author`      VARCHAR(255) NULL,
    `publisher`   VARCHAR(255) NULL,
    `photo_link`  VARCHAR(1000) NULL,
    `floor`       VARCHAR(255) NULL,
    `shelf_name`  VARCHAR(255) NULL,
    `shelf_count` int NULL,
    `book_row`         int NULL,
    `book_cell`        int NULL
);

CREATE TABLE `member`
(
    `member_id`      bigint generated by default as identity,
    `email`          VARCHAR(255) NOT NULL,
    `password`       VARCHAR(255) NOT NULL,
    `favorite_count` int          NOT NULL
);

CREATE TABLE `auth_number`
(
    `auth_id`     bigint generated by default as identity,
    `auth_email`  VARCHAR(255) NOT NULL,
    `auth_number` int          NOT NULL,
    `created_at`  bigint       NOT NULL
);

ALTER TABLE `book`
    ADD CONSTRAINT `PK_BOOK` PRIMARY KEY (
                                          `book_id`
        );

ALTER TABLE `member`
    ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
                                            `member_id`
        );

ALTER TABLE `auth_number`
    ADD CONSTRAINT `PK_AUTH_NUMBER` PRIMARY KEY (
                                                 `auth_id`
        );